#include "rvector.h"
#include "rmatrix.h"
#include "random.h"
#include "joint.h"
#include "fbatdist.h"
#include "defines.h"
#include "datamatrix.h"
extern "C" {

// AUTO-GENERATED by RExport.R

void eREXP_joint(  double *data, int *dimdata, double *marker, int *dimmarker, double *trait, double *env, double *model, double *RET_a, int *dimRET_a, double *RET_b, int *dimRET_b, double *RET_numInf, int *dimRET_numInf ) {
  RMatrix _data;
  _data.set(data,dimdata);
  RVector _marker;
  _marker.set(marker,dimmarker);
  RVector _RET_a;
  _RET_a.set(RET_a,dimRET_a);
  RMatrix _RET_b;
  _RET_b.set(RET_b,dimRET_b);
  RVector _RET_numInf;
  _RET_numInf.set(RET_numInf,dimRET_numInf);

  REXP_joint(_data, _marker, *trait, *env, *model, _RET_a, _RET_b, _RET_numInf );
}



}

